language: go

env:
- GO111MODULE=on

go:
- 1.11rc1

# no need to run go get
install: true

script:
- go build -v -o bin/badgerodon-www .

deploy:
  provider: releases
  api_key:
    secure: BdE58O0et+vN/OF89RedLRrieqQul1/Z3tZQs5bcmZdDlVeKFTX6eb0JTXOOFZr/h8UFy3JAX29lH+ZLEUQXHXVhuiRrFFpM2sQ1tuqrTEaPkrOrv0ybaUif+eFDiUP512xMdC9tR6rkW9L2wXwaGkxr7Lp5fTnDjJxi1ylBmrkn+1QcgjDn3pb5JZKedCjkcvcdsllo6Mp0mYWlfDJpm0XS0dZMeGtUpr2k4wakdpXCeh2PrgEpOByFaHORBgKkxe/AzblQyF8RtWk6qLRrgGQfs3cB9hMm++ruEUGhHPk8fz/n8QJ8jy0JMfHn+mGOfDYlzy9F6NwcTYT1JOVE5IR+jiPDY0ze6xpRBXuX9Mij0XDDAoaj4TRPi0MUsB+C97FKxdO2FaO5EsP2awB1XzeZe72kH+ywPtDf7Yx7e7uwY6PjnN1ilwFRrLiIfsQDZt1+dDiodpTE6dfMrteMZz/lrs2BLjzGsY0POr5mR1rn7E6yelRpkgBqWB+psDoTX2g3x2yAmAnmR2gkGUcuvhtTYrOW6CjVo2zp5fWgCyJjVClvMUyN6UHCXNyAx4csZ8DVDkQmU3640b/8BhgRmOMX9jaloApBOp7GXdKHhc795Me9D/hMkNL6vjKM3NYpljrHAVJ0Cps1TDh+3+wB9IQn8c2PBDnXS4j47ChhPqs=
  file: bin/badgerodon-www
  on:
    repo: badgerodon/www
    tags: true
