language: go

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

services:
- docker

env:
  global:
  - GO111MODULE=on
  - DOCKER_IMAGE=gcr.io/doxsey-1/badgerodon-www:$TRAVIS_COMMIT

go:
- "1.11"

before_install:
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth configure-docker

# no need to run go get
install: true

script:
- go build -v -o bin/badgerodon-www .
- docker build -t $DOCKER_IMAGE .
- docker push $DOCKER_IMAGE
